# Generated by Django 4.0.5 on 2022-06-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_arm', models.CharField(max_length=150, verbose_name="nom d'Arme")),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_dip', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_dir', models.CharField(max_length=150, verbose_name='nom de la direction')),
            ],
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Entite', models.CharField(max_length=50, verbose_name='destinataire ou expediteur')),
                ('service', models.CharField(choices=[('Choix du Service', (('Interne', 'Interne'), ('Externe', 'Externe')))], max_length=50)),
                ('personne', models.CharField(choices=[('Choix du Type de Personne', (('Morale', 'Morale'), ('Physique', 'Physique')))], max_length=50)),
                ('date_creat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_grad', models.CharField(max_length=150, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_TypeServ', models.CharField(max_length=50, verbose_name='type de service')),
            ],
        ),
        migrations.CreateModel(
            name='sousDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de sous direction')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrer.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('sousdirection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrer.sousdirection')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_per', models.CharField(max_length=150, verbose_name='nom')),
                ('pren_per', models.CharField(max_length=150, verbose_name='prenom')),
                ('photo', models.ImageField(null=True, upload_to='static/images', verbose_name='photo')),
                ('dteNaiss_per', models.DateField(verbose_name='date de naissance')),
                ('lieu', models.CharField(max_length=200, null=True, verbose_name='lieu de naissance')),
                ('Mat_per', models.CharField(blank=True, max_length=150, verbose_name='matricule')),
                ('Sex_per', models.CharField(choices=[('Choix du sexe---', (('Feminin', 'Feminin'), ('Masculin', 'masculin')))], max_length=150, null=True, verbose_name='sexe')),
                ('post_per', models.CharField(max_length=150, verbose_name='FONCTION/OCCUPATION')),
                ('Emai_per', models.EmailField(max_length=254, verbose_name='Email')),
                ('tel_per', models.CharField(max_length=100, verbose_name='Telephone')),
                ('numDec', models.CharField(blank=True, max_length=100, null=True, verbose_name='numero de decision')),
                ('dom_per', models.CharField(max_length=150, verbose_name='domicile')),
                ('deco_per', models.CharField(blank=True, max_length=150, null=True, verbose_name='decoration')),
                ('Meca_per', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mecano')),
                ('stage_per', models.CharField(blank=True, max_length=150, null=True, verbose_name='stage effectué')),
                ('Type_per', models.CharField(choices=[('Choisir type personne', (('Civil', 'Civil'), ('Corps_habillé', 'Corps_habillé')))], max_length=150, null=True, verbose_name='type de personne')),
                ('numAr_per', models.IntegerField(blank=True, null=True, verbose_name="numéro d'arme")),
                ('formations', models.CharField(blank=True, max_length=200, null=True, verbose_name='formations')),
                ('situa_pers', models.CharField(choices=[('Choix du situation matrimoniale', (('Marié', 'Marié(e)'), ('celibataire', 'Célibataire')))], max_length=100, verbose_name='situation matrimoniale')),
                ('person', models.CharField(max_length=200, null=True, verbose_name='personne à contacter')),
                ('datePrise', models.DateField(null=True, verbose_name='date prise de service')),
                ('dateEnr', models.DateTimeField(auto_now=True, verbose_name='date d enregistrement')),
                ('dateE', models.DateField(blank=True, null=True, verbose_name="date d'entree à la police")),
                ('AnSer_per', models.CharField(blank=True, max_length=300, null=True, verbose_name='TROIS DERNIERS SERVICE ET POSTE OCCUPES AVANT LA DITT')),
                ('Arme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrer.arme', verbose_name='Arme')),
                ('Diplomes', models.ManyToManyField(related_name='Diplomes', to='administrer.diplome')),
                ('Grades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrer.grade', verbose_name='Grades')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrer.service', verbose_name='service')),
                ('sousdirection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrer.sousdirection')),
            ],
            options={
                'ordering': ['dateE'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ordre_cour', models.IntegerField(null=True, unique=True, verbose_name='numero d ordre')),
                ('date_Emiss_cour', models.DateField(blank=True, null=True, verbose_name='date Emission')),
                ('date_AccuseRecp_cour', models.DateField(blank=True, null=True, verbose_name='date de reception')),
                ('obj_cour', models.TextField()),
                ('type_cour', models.CharField(choices=[('Choix de Type de Courrier', (('TRANSMISSION', 'TRANSMISSION'), ('INTERNE', 'INTERNE'), ('ENTRANT', 'ENTRANT'), ('SORTANT', 'SORTANT')))], max_length=20, null=True)),
                ('num_AccRecp_cour', models.PositiveIntegerField(blank=True, null=True, verbose_name='numero accusé de reception')),
                ('file_cour', models.FileField(null=True, upload_to='static/upload', verbose_name='fichier')),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('DestRecp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DestRecp', to='administrer.entite', verbose_name='destinataire ou recepteur')),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
    ]
