# Generated by Django 4.0.5 on 2022-06-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrer', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Grades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrer.grade', verbose_name='Grades'),
        ),
    ]
