# Generated by Django 4.0.5 on 2022-06-08 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrer', '0003_alter_person_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Arme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrer.arme', verbose_name='Arme'),
        ),
    ]
