# Generated by Django 4.0.5 on 2022-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrer', '0005_alter_person_service_alter_person_sousdirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/images', verbose_name='photo'),
        ),
    ]
