# Generated by Django 4.0.5 on 2022-06-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrer', '0006_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intruc', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observation', models.CharField(max_length=250, null=True)),
                ('courrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courrier', to='administrer.courrier')),
                ('instru', models.ManyToManyField(to='administrer.instruction')),
                ('service', models.ManyToManyField(to='administrer.service')),
            ],
        ),
    ]
