# Generated by Django 4.0.5 on 2022-06-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrer', '0007_instruction_ficheanalyse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courrier',
            options={'permissions': [('view_courrier_dashboard', 'peut etre vu uniquement par le tableau de bords')]},
        ),
    ]
